# Generated by Django 4.2.11 on 2024-07-29 07:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kennel', '0003_rename_breed_dog_breed_name_dog_breed_description'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dog',
            old_name='breed_name',
            new_name='breed',
        ),
        migrations.RenameField(
            model_name='dog_breed',
            old_name='breed_name',
            new_name='breed',
        ),
    ]
