# Generated by Django 4.2.11 on 2024-08-23 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kennel', '0005_dog_sex'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dog',
            name='sex',
            field=models.CharField(choices=[('Pies', 'Pies'), ('Suka', 'Suka')], default='Pies', max_length=20),
        ),
    ]
