# Generated by Django 4.2.11 on 2024-09-16 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kennel', '0006_alter_dog_sex'),
    ]

    operations = [
        migrations.CreateModel(
            name='Puppies',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.CharField(blank=True, max_length=10000)),
                ('image1', models.ImageField(blank=True, upload_to='uploads/puppies/')),
            ],
        ),
    ]
