# Generated by Django 4.2.11 on 2024-09-16 10:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kennel', '0007_puppies'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='puppies',
            options={'verbose_name': 'Szczenięta', 'verbose_name_plural': 'Szczenięta'},
        ),
    ]
