# Generated by Django 4.2.11 on 2024-10-20 13:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kennel', '0008_alter_puppies_options'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Puppies',
        ),
    ]
