# Generated by Django 4.2.11 on 2024-12-09 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kennel', '0009_delete_puppies'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dog',
            old_name='awards',
            new_name='awards_EN',
        ),
        migrations.AddField(
            model_name='dog',
            name='awards_PL',
            field=models.CharField(blank=True, max_length=10000),
        ),
    ]
