# Generated by Django 4.2.11 on 2024-07-26 11:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blog_post',
            old_name='artice',
            new_name='article',
        ),
    ]
