# Generated by Django 4.2.11 on 2024-07-26 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carousel_items',
            name='image',
            field=models.ImageField(blank=True, upload_to='uploads/carousel/'),
        ),
    ]
