# Generated by Django 4.2.11 on 2024-07-26 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_gellery_items_alter_carousel_items_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='gellery_items',
            name='category',
            field=models.CharField(choices=[('wystawy', 'Wystawy'), ('codzienne', 'Życie Codzienne'), ('szczenieta', 'Szczenięta'), ('education', 'Education')], default='wystawy', max_length=20),
        ),
    ]
