# Generated by Django 4.2.11 on 2024-07-27 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0004_gellery_items_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gellery_items',
            name='category',
            field=models.CharField(choices=[('wystawy', 'Wystawy'), ('codzienne', 'Życie Codzienne'), ('szczenieta', 'Szczenięta')], default='wystawy', max_length=20),
        ),
    ]
