# Generated by Django 4.2.11 on 2024-10-10 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0005_alter_gellery_items_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sections',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=100)),
                ('text_PL', models.CharField(blank=True, max_length=10000)),
                ('text_EN', models.CharField(blank=True, max_length=10000)),
            ],
            options={
                'verbose_name': 'Treści Strony',
                'verbose_name_plural': 'Treści Strony',
            },
        ),
    ]
