# Generated by Django 4.2.11 on 2024-10-17 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0007_curr_lang'),
    ]

    operations = [
        migrations.CreateModel(
            name='Puppies',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=100)),
                ('article', models.CharField(blank=True, max_length=10000)),
                ('image', models.ImageField(blank=True, upload_to='uploads/puppies/')),
            ],
            options={
                'verbose_name': 'Elementy Szczeniąt',
                'verbose_name_plural': 'Elementy Szczeniąt',
            },
        ),
        migrations.DeleteModel(
            name='Curr_Lang',
        ),
        migrations.DeleteModel(
            name='Sections',
        ),
    ]
