# Generated by Django 4.2.11 on 2024-10-17 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0008_puppies_delete_curr_lang_delete_sections'),
    ]

    operations = [
        migrations.AlterField(
            model_name='puppies',
            name='article',
            field=models.CharField(blank=True, max_length=1000),
        ),
    ]
