# Generated by Django 4.2.11 on 2024-10-20 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0009_alter_puppies_article'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='puppies',
            name='article',
        ),
        migrations.RemoveField(
            model_name='puppies',
            name='title',
        ),
        migrations.AddField(
            model_name='puppies',
            name='period',
            field=models.CharField(choices=[('jesien', 'Jesień'), ('zima', 'Zima'), ('wiosna', 'Wiosna'), ('lato', 'Lato')], default='jesien', max_length=20),
        ),
        migrations.AddField(
            model_name='puppies',
            name='year',
            field=models.CharField(choices=[('2024', '2024'), ('2025', '2025'), ('2026', '2026'), ('2027', '2027'), ('2028', '2028'), ('2029', '2029'), ('2030', '2030'), ('2031', '2031'), ('2032', '2032'), ('2033', '2033'), ('2034', '2034')], default='2024', max_length=20),
        ),
    ]
