# Generated by Django 4.2.11 on 2024-10-22 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0011_alter_puppies_period'),
    ]

    operations = [
        migrations.AddField(
            model_name='puppies',
            name='rasa',
            field=models.CharField(choices=[('Bolończyk', 'Bolończyk'), ('Rosyjska Bolonka Kolorowa', 'Rosyjska Bolonka Kolorowa')], default='Bolończyk', max_length=100),
        ),
    ]
