# Generated by Django 4.2.11 on 2024-12-09 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0012_puppies_rasa'),
    ]

    operations = [
        migrations.AddField(
            model_name='puppies',
            name='description_EN',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='puppies',
            name='description_PL',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
