# Generated by Django 4.2.11 on 2024-12-09 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0013_puppies_description_en_puppies_description_pl'),
    ]

    operations = [
        migrations.AlterField(
            model_name='puppies',
            name='description_EN',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='puppies',
            name='description_PL',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='puppies',
            name='period',
            field=models.CharField(blank=True, choices=[('jesień', 'Jesień'), ('zima', 'Zima'), ('wiosna', 'Wiosna'), ('lato', 'Lato')], default='jesień', max_length=20),
        ),
        migrations.AlterField(
            model_name='puppies',
            name='rasa',
            field=models.CharField(blank=True, choices=[('Bolończyk', 'Bolończyk'), ('Rosyjska Bolonka Kolorowa', 'Rosyjska Bolonka Kolorowa')], default='Bolończyk', max_length=100),
        ),
        migrations.AlterField(
            model_name='puppies',
            name='year',
            field=models.CharField(blank=True, choices=[('2024', '2024'), ('2025', '2025'), ('2026', '2026'), ('2027', '2027'), ('2028', '2028'), ('2029', '2029'), ('2030', '2030'), ('2031', '2031'), ('2032', '2032'), ('2033', '2033'), ('2034', '2034')], default='2024', max_length=20),
        ),
    ]
